### ISSUE TITLE
@angular/compiler-cli needs to be 2.3.1 or greater. 

### ISSUE THREAD

**Issue by desbond** [MurhafSousli/8puzzle#2]
Hi Do you know how to fix this problem :+1: 
After npm start :

Error: Version of @angular/compiler-cli needs to be 2.3.1 or greater. Current version is "undefined"

**Comment by MurhafSousli** [comment]
Hi @desbond, this project is 5 months old, you probably have a newer version of `angular-cli` which uses different code for `npm start`, I suggest you create a new project and then copy the code to it
